#
# Makefile for frandom
# 

obj-$(CONFIG_FRANDOM)  := frandom.o 

#KERNEL_DIR=/home/mrd/Descargas/Undervolting/package/MyKernel/
#ifneq ($(KERNELRELEASE),)
#obj-m	:= frandom.o

#else
#KDIR := /lib/modules/$(shell uname -r)/build
#PWD := $(shell pwd)

#default:
#        $(MAKE) ARCH=arm CROSS_COMPILE=/home/kernel/android-toolchain-eabi-4-4/bin/arm-eabi- -C $(KERNEL_DIR) SUBDIRS=$(PWD) modules
#clean:
#        $(MAKE) -C $(KERNEL_DIR) SUBDIRS=$(PWD) clean
#default:
#	$(MAKE) -C $(KDIR) SUBDIRS=$(PWD) modules
#endif

